CREATE TABLE "SIA_REQUISITIONS" 
   (	"REQUISITION_LINE" NUMBER, 
	"REQUISITION" NUMBER, 
	"SYNC_DATE" DATE, 
	"CREATED_DATE" DATE
   );
   CREATE UNIQUE INDEX "SIA_REQUISITIONS_PK" ON "SIA_REQUISITIONS" ("REQUISITION_LINE", "REQUISITION");
   ALTER TABLE "SIA_REQUISITIONS" ADD CONSTRAINT "SIA_REQUISITIONS_PK" PRIMARY KEY ("REQUISITION_LINE", "REQUISITION");