//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 11:18:07 AM EDT 
//


package trax.aero.outbound;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import trax.aero.inbound.Order;



@XmlRootElement(name="MT_TRAX_I41_ACK_4067", namespace="http://singaporeair.com/mro/TRAX")
@XmlAccessorType(XmlAccessType.FIELD)
public class DTTRAXI41ACK4067
{
	@XmlElement(name = "SuccessErrorLog")
    private SuccessErrorLog SuccessErrorLog;
	
	@XmlElement(name = "Orders")
	private ArrayList<Orders> Orders;
	
	

    public SuccessErrorLog getSuccessErrorLog ()
    {
        return SuccessErrorLog;
    }

    public void setSuccessErrorLog (SuccessErrorLog SuccessErrorLog)
    {
        this.SuccessErrorLog = SuccessErrorLog;
    }

    public ArrayList<Orders> getOrders ()
    {
        return Orders;
    }

    public void setOrders (ArrayList<Orders> Orders)
    {
        this.Orders = Orders;
    }
    
    
   
}
